#!/usr/bin/env bash
# gen_filelist.sh — emit a slang command-file (design.f) for `sv_elaborate` of niigo_soc,
# mirroring fpga/synth/run_soc.sh's source set but for the OpenROAD/yosys-slang flow.
#
#   - Defines the full FPGA/ASIC config (RV64 OoO + L1I/L1D + AXI + FPGA_BUILD + SYNTHESIS).
#   - Includes the CVFPU source set (curated list from src/verilator.mk), then src/*.sv +
#     src/mem/*.sv, EXCLUDING the sim/alt/lab files AND the multicore CCD/CMI files (not in
#     the niigo_soc cone). slang elaborates from --top, so file order does not matter.
#   - Stages lzc.sv / rr_arb_tree.sv with `default_nettype none`->`wire` (same shim as run_soc.sh).
#
# Usage: gen_filelist.sh [BUILD_DIR]   (default: <repo>/output/openroad)
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
BUILD="${1:-$ROOT/output/openroad}"
mkdir -p "$BUILD"
F="$BUILD/design.f"

# sim/alt/lab files (same as run_soc.sh EXCLUDE) + the alt cores + sim NMI/AXI backends
EXCL_SIM='testbench main_memory sram_simulation cache cache_new register_file riscv_core_timing riscv_core riscv_core_scalar riscv_core_4wide nmi_mem_adapter axi_mem_shim axi_chk'
# multicore CCD/CMI files — present in src/mem but NOT instantiated by single-core niigo_soc
EXCL_CCD='cmi_agent_downlink cmi_agent_uplink cmi_hub_dir_rx cmi_msg_rx cmi_msg_tx cmi_router cmi_wheel niigo_ccd_top niigo_ccd_gg_direct niigo_ccd_gg_wheel niigo_ccd_wheel niigo_dir niigo_dir_gg niigo_l1d_moesi niigo_l1d_gg'
excluded() { local b; b="$(basename "$1" .sv)"; for x in $EXCL_SIM $EXCL_CCD; do [ "$b" = "$x" ] && return 0; done; return 1; }

# default_nettype shim for the two un-terminated common_cells (matches run_soc.sh)
for f in lzc.sv rr_arb_tree.sv; do
  sed 's/`default_nettype none/`default_nettype wire/' "$ROOT/src/common_cells/$f" > "$BUILD/$f"
done

# header: include dirs + defines
{
  echo "// auto-generated by gen_filelist.sh — slang command file for sv_elaborate (top=niigo_soc)"
  for d in src src/mem src/common_cells src/cvfpu/src src/cvfpu/vendor \
           src/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl \
           src/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl \
           src/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl \
           src/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl; do
    echo "+incdir+$ROOT/$d"
  done
  for D in RV64 OOO_4WIDE L1_CACHES L1D_CACHE AXI_MEMSYS FPGA_BUILD SYNTHESIS; do echo "+define+$D"; done
} > "$F"

# LAB_18447 is a STRING-valued macro (`LAB_18447 == "4a" ...). slang drops the value
# from a command-file `+define+LAB_18447="4b"` (expands empty -> parse error), so define
# it in a leading source file instead; under --single-unit it is visible design-wide.
printf '`define LAB_18447 "4b"\n' > "$BUILD/or_defines.svh"
echo "$BUILD/or_defines.svh" >> "$F"

# CVFPU sources: pull the curated $(CVFPU_DIR)/... paths straight out of verilator.mk
grep -oE '\$\(CVFPU_DIR\)/[^ \\]+\.(sv|v)' "$ROOT/src/verilator.mk" \
  | sed "s#\$(CVFPU_DIR)#$ROOT/src/cvfpu#" >> "$F"

# niigo RTL: src/*.sv then src/mem/*.sv minus the exclude sets; then the staged common_cells
for f in "$ROOT"/src/*.sv "$ROOT"/src/mem/*.sv; do excluded "$f" || echo "$f"; done >> "$F"
echo "$BUILD/lzc.sv"         >> "$F"
echo "$BUILD/rr_arb_tree.sv" >> "$F"

n=$(grep -cE '\.(sv|v)$' "$F")
echo "wrote $F  ($n source files; top = niigo_soc)"
